server:
  port: 9002

spring:
  application:
    name: user-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    srevice-url:
      defaultZone: http://127.0.0.1:8761/eureka